run:
  go: "1.20"

issues:
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - asciicheck
    - bodyclose
    #- cyclop
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    #- exhaustivestruct
    - exportloopref
    - forcetypeassert
    # - funlen
    # - gci
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - goimports
    - gomnd
    - gosec
    - ifshort
    #- lll
    - misspell
    - nakedret
    #- nlreturn
    - noctx
    # - nolintlint
    - paralleltest
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - wastedassign
    - whitespace
linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
