package main

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// tapes are the VHS scripts that render the GIFs README embeds, paired with the
// image each one produces.
var tapes = []struct {
	tape string
	gif  string
}{
	{tape: "doc/img/demo.tape", gif: "doc/img/demo.gif"},
	{tape: "doc/img/pipe.tape", gif: "doc/img/pipe.gif"},
}

// TestDemoTapesStillWork runs the commands each VHS tape types and requires the
// whole session to succeed.
//
// A GIF cannot be regenerated byte-for-byte (VHS output varies with timing,
// fonts and the encoder), so CI cannot diff it to prove the demo is current.
// What can be checked deterministically is the thing that actually rots: the
// command lines inside the tape. Rename a subcommand or change a flag and this
// fails here, instead of the next `make demo` quietly recording a terminal full
// of usage errors -- `vhs` exits 0 no matter what appears on screen.
//
// The lines run as one bash script rather than one command at a time, because
// the demo is a session: `jws sign` writes token.jws for the next line to read,
// and the pipe tape assigns `token=$(cat token.jws)` before using $token.
func TestDemoTapesStillWork(t *testing.T) {
	t.Parallel()

	bash, err := exec.LookPath("bash")
	if err != nil {
		t.Skip("bash not available; the tapes declare `Set Shell bash`")
	}
	binDir := buildJoseForTape(t)

	for _, tc := range tapes {
		t.Run(tc.tape, func(t *testing.T) {
			t.Parallel()

			script := shellLinesInTape(t, tc.tape)
			if script == "" {
				t.Fatalf("%s types no commands; the tape or this parser is wrong", tc.tape)
			}

			// The same seed `make demo` lays down before running vhs.
			dir := t.TempDir()
			if err := os.WriteFile(filepath.Join(dir, "payload.json"), []byte(`{"sub":"alice"}`), 0o600); err != nil {
				t.Fatal(err)
			}

			// -e so the first failing command fails the test rather than the
			// session limping on to the end and exiting 0.
			cmd := exec.CommandContext(t.Context(), bash, "-e", "-c", script)
			cmd.Dir = dir
			cmd.Env = append(os.Environ(),
				"PATH="+binDir+string(os.PathListSeparator)+os.Getenv("PATH"),
				"GOEXPERIMENT=jsonv2",
			)

			if out, err := cmd.CombinedOutput(); err != nil {
				t.Errorf("%s failed: %v\nscript:\n%s\noutput:\n%s", tc.tape, err, script, out)
			}
		})
	}
}

// TestDemoTapesRenderTheReadmeGIFs pins that each tape still produces the image
// README embeds. A tape that renders somewhere else leaves the README showing a
// stale GIF with nothing failing.
func TestDemoTapesRenderTheReadmeGIFs(t *testing.T) {
	t.Parallel()

	readme, err := os.ReadFile("README.md")
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range tapes {
		if !strings.Contains(string(readme), "./"+tc.gif) {
			t.Errorf("README.md no longer embeds ./%s; %s renders it for nobody", tc.gif, tc.tape)
		}
		// The tape writes a bare filename that `make demo` moves into doc/img/,
		// so what is pinned here is that basename.
		tape, err := os.ReadFile(tc.tape) //nolint:gosec // a test-supplied path inside the repository
		if err != nil {
			t.Fatal(err)
		}
		if want := "Output " + filepath.Base(tc.gif); !strings.Contains(string(tape), want) {
			t.Errorf("%s does not %q", tc.tape, want)
		}
	}
}

// buildJoseForTape builds the CLI and returns the directory holding it.
func buildJoseForTape(t *testing.T) string {
	t.Helper()

	goBin, err := exec.LookPath("go")
	if err != nil {
		t.Skip("go toolchain not available; cannot build the binary the tapes drive")
	}
	binDir := t.TempDir()
	build := exec.CommandContext(context.Background(), goBin, "build", "-o", filepath.Join(binDir, "jose"), ".")
	build.Env = append(os.Environ(), "GOEXPERIMENT=jsonv2")
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("go build failed: %v\n%s", err, out)
	}
	return binDir
}

// shellLinesInTape returns the commands a VHS tape types, in order, as one
// script. Lines typed between `Hide` and `Show` are the tape's own scaffolding
// -- they export a PATH and cd into a directory `make demo` created -- and the
// test supplies its own equivalents, so they are skipped.
func shellLinesInTape(t *testing.T, path string) string {
	t.Helper()

	data, err := os.ReadFile(path) //nolint:gosec // a test-supplied path inside the repository
	if err != nil {
		t.Fatal(err)
	}

	var lines []string
	hidden := false
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		switch line {
		case "Hide":
			hidden = true
			continue
		case "Show":
			hidden = false
			continue
		}
		if hidden || !strings.HasPrefix(line, `Type "`) {
			continue
		}
		// `Type "..." Enter` puts the Enter on the same line.
		typed := strings.TrimPrefix(line, `Type "`)
		end := strings.LastIndex(typed, `"`)
		if end < 0 {
			continue
		}
		lines = append(lines, strings.ReplaceAll(typed[:end], `\\`, `\`))
	}
	return strings.Join(lines, "\n")
}
